name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/custom-sonos-card/custom-sonos-card
          npm install
          npm run build

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/custom-sonos-card/custom-sonos-card/dist/custom-sonos-card.js
          asset_name: custom-sonos-card.js
          tag: ${{ github.ref }}
          overwrite: true
